# Default initial positions for the panda arm's ros2_control fake system
# 熊猫臂的 ros2_control 模拟系统的默认初始位置
initial_positions:
  panda_joint1: 0.0
  panda_joint2: -0.785
  panda_joint3: 0.0
  panda_joint4: -2.356
  panda_joint5: 0.0
  panda_joint6: 1.571
  panda_joint7: 0.785
